# 0 Setup

In [63]:
from pathlib import Path
import sys

repo_path = Path.cwd().resolve()
if repo_path.name == 'notebooks':
    repo_path = repo_path.parent
sys.path.insert(0, str(repo_path))

from src.config import SAMPLE_SUBMISSION, TEST_RAW, TRAIN_RAW, repo_root

print(f'Repository root: {repo_root()}')
for raw_path in (TRAIN_RAW, TEST_RAW, SAMPLE_SUBMISSION):
    print(f'{raw_path.name} exists: {raw_path.exists()}')

Repository root: C:\Users\SKY\Documents\Pink Ai
pinkai_train.csv exists: True
pinkai_test.csv exists: True
sample_submission.csv exists: True

# 1 Load and inspect

Load both raw files as text, preserving cell values.

In [64]:
from IPython.display import display

from src.load import load_test, load_train
from src.inspect_data import (
    category_values,
    comma_decimal_count,
    date_samples,
    empty_cell_counts,
    id_report,
    label_counts,
    measurement_columns,
    non_numeric_cells,
    numeric_ranges,
    odd_column_names,
    shape_summary,
)

train = load_train()
test = load_test()
measurement_cols = measurement_columns(train)["column"].tolist()
print(f"Loaded train: {train.shape}; test: {test.shape}; measurement columns: {len(measurement_cols)}")

Loaded train: (9000, 38); test: (3000, 37); measurement columns: 30

Compare row and column counts and file-specific columns.

In [65]:
display(shape_summary(train, test))

{'train_shape': (9000, 38),
 'test_shape': (3000, 37),
 'train_only_columns': ['diagnosis'],
 'test_only_columns': []}

List column names that do not match lowercase letters and underscores.

In [66]:
print("Train odd column names")
display(odd_column_names(train))
print("Test odd column names")
display(odd_column_names(test))

Train odd column names

         column_name
0       Texture_Mean
1     perimeter mean
2  concave points_se
3         AREA_WORST

Test odd column names

         column_name
0       Texture_Mean
1     perimeter mean
2  concave points_se
3         AREA_WORST

Count each raw diagnosis spelling in the training file.

In [67]:
display(label_counts(train).head(15))

     raw_value  count
0      benign    1078
1       Benign   1074
2            B   1066
3            0   1020
4            B    979
5            M    740
6            1    700
7    malignant    627
8    MALIGNANT    626
9            m    618
10          B      21
11           B     15
12  \tbenign       14
13        \t0      12
14           B     12

Count blank, whitespace-only, and literal nan cells by column.

In [68]:
print("Train empty-like cells")
display(empty_cell_counts(train).head(15))
print("Test empty-like cells")
display(empty_cell_counts(test).head(15))

Train empty-like cells

                    column  empty_count  empty_percent
0                    notes         4297      47.744444
1            smoothness_se          539       5.988889
2          smoothness_mean          534       5.933333
3         smoothness_worst          528       5.866667
4               AREA_WORST          298       3.311111
5        compactness_worst          295       3.277778
6   fractal_dimension_mean          294       3.266667
7           symmetry_worst          289       3.211111
8     fractal_dimension_se          283       3.144444
9            texture_worst          282       3.133333
10         perimeter_worst          281       3.122222
11           symmetry_mean          279       3.100000
12    concave_points_worst          278       3.088889
13       concave points_se          272       3.022222
14         concavity_worst          272       3.022222

Test empty-like cells

                    column  empty_count  empty_percent
0                    notes         1448      48.266667
1         smoothness_worst          180       6.000000
2          smoothness_mean          172       5.733333
3            smoothness_se          150       5.000000
4                area_mean          112       3.733333
5          perimeter_worst          106       3.533333
6          concavity_worst          103       3.433333
7     fractal_dimension_se           99       3.300000
8             radius_worst           98       3.266667
9           symmetry_worst           98       3.266667
10  fractal_dimension_mean           97       3.233333
11              AREA_WORST           96       3.200000
12        compactness_mean           95       3.166667
13          perimeter mean           95       3.166667
14          compactness_se           94       3.133333

Count measurement cells written with comma decimal separators.

In [69]:
print("Train comma-decimal counts")
display(comma_decimal_count(train, measurement_cols).head(15))
print("Test comma-decimal counts")
display(comma_decimal_count(test, measurement_cols).head(15))

Train comma-decimal counts

                    column  comma_decimal_count
0              radius_mean                  324
1             Texture_Mean                  332
2           perimeter mean                  297
3                area_mean                  317
4          smoothness_mean                  314
5         compactness_mean                  360
6           concavity_mean                  331
7      concave_points_mean                  345
8            symmetry_mean                  300
9   fractal_dimension_mean                  338
10               radius_se                  322
11              texture_se                  330
12            perimeter_se                  358
13                 area_se                  329
14           smoothness_se                  325

Test comma-decimal counts

                    column  comma_decimal_count
0              radius_mean                  101
1             Texture_Mean                  107
2           perimeter mean                  115
3                area_mean                  108
4          smoothness_mean                   96
5         compactness_mean                  127
6           concavity_mean                  106
7      concave_points_mean                  109
8            symmetry_mean                  105
9   fractal_dimension_mean                  111
10               radius_se                  109
11              texture_se                  106
12            perimeter_se                  102
13                 area_se                  111
14           smoothness_se                  116

Count unparseable non-empty measurement values and show examples.

In [70]:
print("Train non-numeric measurement values")
display(non_numeric_cells(train, measurement_cols).head(15))
print("Test non-numeric measurement values")
display(non_numeric_cells(test, measurement_cols).head(15))

Train non-numeric measurement values

,column,non_numeric_count,example_bad_values
0,radius_mean,142,"[n/a, ?, NULL, missing, unknown]"
1,Texture_Mean,163,"[?, N/A, n/a, unknown, --]"
2,perimeter mean,154,"[unknown, -, --, NULL, n/a]"
3,area_mean,680,"[1,419.5, 1,067.1, 1,310.0, 1,041.0, 1,062.7]"
4,smoothness_mean,161,"[missing, n/a, N/A, unknown, NULL]"
5,compactness_mean,159,"[NULL, unknown, N/A, missing, -]"
6,concavity_mean,156,"[missing, unknown, N/A, -, n/a]"
7,concave_points_mean,172,"[NULL, n/a, N/A, -, --]"
8,symmetry_mean,171,"[NULL, unknown, -, N/A, --]"
9,fractal_dimension_mean,198,"[-, ?, n/a, missing, N/A]"
10,radius_se,179,"[?, -, N/A, unknown, n/a]"
11,texture_se,172,"[--, n/a, NULL, N/A, -]"
12,perimeter_se,184,"[N/A, -, n/a, --, NULL]"
13,area_se,180,"[33,571.8, --, n/a, unknown, 20,324.1]"
14,smoothness_se,169,"[-, missing, N/A, n/a, unknown]"

Test non-numeric measurement values

,column,non_numeric_count,example_bad_values
0,radius_mean,52,"[NULL, -, ?, unknown, --]"
1,Texture_Mean,60,"[--, NULL, n/a, unknown, ?]"
2,perimeter mean,60,"[unknown, missing, N/A, ?, --]"
3,area_mean,141,"[missing, 1,080.5, 1,038.2, 1,233.7, 1,579.6]"
4,smoothness_mean,62,"[?, n/a, N/A, -, unknown]"
5,compactness_mean,60,"[missing, NULL, n/a, -, ?]"
6,concavity_mean,61,"[unknown, -, N/A, --, NULL]"
7,concave_points_mean,53,"[missing, unknown, --, -, ?]"
8,symmetry_mean,55,"[n/a, --, ?, -, missing]"
9,fractal_dimension_mean,76,"[missing, N/A, n/a, ?, NULL]"
10,radius_se,62,"[NULL, N/A, ?, missing, --]"
11,texture_se,52,"[?, -, missing, NULL, n/a]"
12,perimeter_se,56,"[unknown, NULL, --, ?, N/A]"
13,area_se,68,"[N/A, --, 19,533.6, missing, 26,044.9]"
14,smoothness_se,69,"[unknown, --, n/a, ?, -]"

Report repeated IDs, exact duplicate rows, unique IDs, and train-test overlap.

In [71]:
display(id_report(train, test))

{'train_duplicate_patient_id_rows': 346,
 'test_duplicate_patient_id_rows': 116,
 'train_identical_duplicate_rows': 173,
 'test_identical_duplicate_rows': 58,
 'train_unique_patient_ids': 8654,
 'test_unique_patient_ids': 2884,
 'shared_patient_ids': [],
 'shared_patient_id_count': 0}

Show raw values of center and biopsy_followup_code in both files.

In [72]:
for column in ("center", "biopsy_followup_code"):
    print(f"Train {column}")
    display(category_values(train, column).head(15))
    print(f"Test {column}")
    display(category_values(test, column).head(15))

Train center

    raw_value  count
0      Site A   3308
1      Site B   2835
2      Site C   1977
3      SITE A    166
4      SITE B    149
5      SITE C     85
6     Site B      36
7      Site A     35
8      Site C     32
9     Site A      31
10     Site B     31
11     Site A     30
12    Site A      29
13    Site B      28
14   \tSite A     25

Test center

    raw_value  count
0      Site A   1029
1      Site B    987
2      Site C    649
3      SITE A     64
4      SITE B     56
5      SITE C     36
6     Site B      15
7   \tSite A      15
8      Site B     14
9     Site B      14
10     Site A     13
11     Site A     11
12    Site A      10
13     Site B      9
14   \tSite B      9

Train biopsy_followup_code

  raw_value  count
0   ROUTINE   5362
1   ONC-REF   3449
2   RECHECK    189

Test biopsy_followup_code

  raw_value  count
0   ROUTINE   2300
1   ONC-REF    625
2   RECHECK     75

Sample raw exam dates reproducibly from each file.

In [73]:
print("Train exam_date sample")
display(date_samples(train, n=15))
print("Test exam_date sample")
display(date_samples(test, n=15))

Train exam_date sample

            exam_date
0          17/09/2025
1           13-Apr-26
2           30-Nov-25
3          2026-06-06
4   November 13, 2025
5          2026-06-15
6           12-Nov-25
7          2025-05-02
8          16/01/2026
9           27-May-25
10          03-May-25
11          08-Oct-25
12      June 13, 2025
13          31-Oct-25
14      April 4, 2025

Test exam_date sample

           exam_date
0          27-Feb-26
1   January 26, 2026
2          07-May-26
3          25-Feb-25
4         28/11/2025
5         27/05/2026
6         29/01/2026
7          30-Jun-26
8          09-Dec-25
9         2026-09-16
10     July 18, 2025
11        2026-04-14
12        25/06/2026
13        20/08/2026
14        2025-09-18

List measurement columns and inspect training numeric ranges for unusual units.

In [74]:
print(f"Measurement columns ({len(measurement_cols)})")
print(measurement_cols)
display(numeric_ranges(train, measurement_cols).head(15))

Measurement columns (30)
['radius_mean', 'Texture_Mean', 'perimeter mean', 'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean', 'concave_points_mean', 'symmetry_mean', 'fractal_dimension_mean', 'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se', 'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se', 'fractal_dimension_se', 'radius_worst', 'texture_worst', 'perimeter_worst', 'AREA_WORST', 'smoothness_worst', 'compactness_worst', 'concavity_worst', 'concave_points_worst', 'symmetry_worst', 'fractal_dimension_worst']

,column,min,p01,median,p99,max
0,radius_mean,0.500000,1.057204,13.341250,24.912284,2.030953e+04
1,Texture_Mean,9.468410,11.139467,18.892800,31.972451,2.916305e+04
2,perimeter mean,32.761600,53.484908,89.230000,736.136000,5.603466e+05
3,area_mean,-452.200000,84.506000,551.500000,1830.861000,1.272592e+06
4,smoothness_mean,0.052706,0.068676,0.095923,0.139117,1.159700e+02
5,compactness_mean,0.014003,0.033932,0.095090,0.284765,2.846800e+02
6,concavity_mean,0.000000,0.000000,0.071199,0.391361,3.175000e+02
7,concave_points_mean,0.000000,0.000000,0.037408,0.182826,1.640000e+02
8,symmetry_mean,0.094759,0.129867,0.179513,0.266970,2.067900e+02
9,fractal_dimension_mean,0.046436,0.051028,0.061602,0.090196,7.408310e+01
10,radius_se,0.000000,0.112605,0.341431,1.525298,7.416700e+02
11,texture_se,0.299562,0.416582,1.121045,3.208710,2.906700e+03
12,perimeter_se,0.754480,0.973724,2.321810,10.106700,7.231500e+03
13,area_se,-450.800000,7.300000,26.700000,231.414000,1.278006e+05
14,smoothness_se,0.000907,0.002950,0.006382,0.018561,1.096640e+01

## What we saw

### 1. Size and structure
- Train has 9,000 rows and 38 columns. Test has 3,000 rows and 37 columns. The only column test lacks is `diagnosis` (the answer), which is correct.
- 30 columns are the real measurements (10 properties x mean / se / worst). The other columns are admin: `patient_id`, `exam_date`, `center`, `age`, `biopsy_followup_code`, `notes`, `sample_ref`.
- Four column names are inconsistent: `Texture_Mean`, `perimeter mean`, `concave points_se`, `AREA_WORST`. Same problem in train and test. We rename everything to lowercase_with_underscores.

### 2. The answer column (`diagnosis`) is written many ways
- Benign appears as `B`, ` B`, `Benign`, `benign `, `0` and more. Malignant appears as `M`, `m`, `MALIGNANT`, `malignant`, `1` and more.
- The top 10 spellings cover about 8,500 of the 9,000 rows, so a few rarer spellings are hidden further down. We must check them all when we clean.
- Roughly 4 in 10 patients are malignant, 6 in 10 benign. This is not extremely imbalanced.

### 3. Numbers are stored as messy text
- **Comma as decimal point:** `1,02967` means 1.02967. It appears in hundreds of cells in almost every measurement column (e.g. 360 in `compactness_mean`).
- **Comma as thousands separator:** `1,419.5` in `area_mean` means 1419.5. This is the OPPOSITE meaning of the comma! If we blindly replace "," with ".", we break these (it becomes `1.419.5`). Rule needed: if a value contains both a comma and a dot, remove the comma; if it has only a comma, treat it as the decimal point.
- **Fake missing values:** `n/a`, `?`, `NULL`, `missing`, `unknown`, `-`, `--`. All of these must become real missing values (NaN).

### 4. Missing values
- `smoothness_mean`, `smoothness_se`, `smoothness_worst` are each missing in about 6% of rows, the highest among measurements. Other measurements have fewer gaps.
- `notes` is empty in about 48% of rows (both files) and also contains both English and Arabic text.
- Missing values will be filled using training-file statistics only (never test).

### 5. Impossible and wrong-unit values (the "wrong units" trap)
- Normal `area_mean` is around 550 (median) and 99% of values are below about 1,830. But the maximum is 1,272,592 and the minimum is NEGATIVE (-452). Area cannot be negative.
- `radius_mean`: median 13.3, maximum 20,309. `perimeter mean`: median 89, maximum 560,346.
- So some rows were recorded in a different unit (values hugely too big), and some have sign errors. Plan: use the geometry link (perimeter ~ 2 x pi x radius, area ~ pi x radius^2) to detect these rows and repair them, not delete them. Note the size of the jump is not exactly the same in every column, so we must investigate before choosing the fix.

### 6. Duplicates
- Train: 8,654 unique patients in 9,000 rows, so 346 extra rows. Of those, 173 are exact copies, and the other 173 share a `patient_id` but have different values (the same patient entered twice with different numbers).
- Test: 2,884 unique patients in 3,000 rows (116 extra, 58 exact copies, 58 with conflicting values). This is why the submission needs exactly 2,884 rows, one per unique ID.
- No patient appears in both train and test. Good, no cheating possible there.
- For validation we must keep all rows of a patient on the same side (group by `patient_id`).

### 7. Dates and centres
- Dates come in at least four formats: `2026-06-06`, `17/09/2025`, `13-Apr-26`, `November 13, 2025`. Slash dates may be day/month or month/day, which can be confusing. We need a consistent rule.
- `center` is Site A / B / C, but with upper-case and extra-space variants (`SITE A`, ` Site B `). After cleaning there should be exactly 3 centres.

### 8. Signs that the test set is different from train (important for the threshold)
- `biopsy_followup_code`: in train, ONC-REF is 38% of rows (3,449 / 9,000) and ROUTINE is 60%. In test, ONC-REF is only about 21% (625 / 3,000) and ROUTINE about 77%.
- We already know ONC-REF goes with cancer (a likely leak, to be proved in Stage 5). If that holds, the test set has noticeably FEWER malignant cases than train. That means more of our predicted "M" would be false alarms, so precision would drop on test.
- Therefore: choose a threshold with a safety margin (aim for ~0.93-0.95 precision in validation, not 0.90), and also test how the model behaves under a lower share of malignant cases.
- Centre mix looks similar between train and test, so the difference is not mainly about centres.

### 9. Suspicious columns (to check in Stage 5)
- `biopsy_followup_code` (probable leak), `sample_ref` (lab tracking code), `notes` (free text, mixed languages).

### Things to do next (Stage 3 and 4)
1. Rename columns. 2. Parse numbers with the comma rule above and turn fake-missing text into NaN. 3. Standardise labels to 0/1 and centres to A/B/C. 4. Convert dates. 5. Fix negative and wrong-unit values by repair. 6. Handle duplicates (drop exact copies, decide what to do with conflicting ones). 7. Fill gaps using train-only statistics.

### Numbers to remember
9,000 / 3,000 rows | 30 measurement columns | 8,654 / 2,884 unique patients | 173 exact + 173 conflicting duplicates in train | about 6% missing smoothness | about 48% empty notes | 0 shared IDs | ONC-REF 38% in train vs 21% in test

# 2 Cleaning

## What we fixed (stage 3)

All fixes are fixed rules (nothing learned from data), so they were applied identically to train (9,000 rows) and test (3,000 rows). Raw files were never edited. Cleaned copies are in `data/clean/`.

1. **Column names:** 4 inconsistent names (`Texture_Mean`, `perimeter mean`, `concave points_se`, `AREA_WORST`) renamed to lowercase_with_underscores. All 38 columns now match the data dictionary.
2. **Fake missing values:** text such as `n/a` (1,312), `?` (614), `null` (650), `missing` (617), `unknown` (623), `-` (721) and `--` (681) turned into real NaN in the numeric columns. Blank cells were also converted. Nothing was left unparseable afterwards.
3. **Numbers stored as text:** 9,919 cells with a decimal comma (`1,02967` -> 1.02967) and 1,389 cells with a thousands comma (`1,419.5` -> 1419.5), each handled by its own rule. The rule: a comma plus a dot means thousands separator, a comma alone means decimal point.
4. **Labels:** 9 spellings of the diagnosis mapped to two classes, with 0 unrecognised values. Train = 5,494 benign (61.0%) and 3,506 malignant (39.0%).
5. **Centres:** upper-case and whitespace variants standardised to exactly 3 centres: Site A (3,655), Site B (3,150), Site C (2,195) in train.
6. **Dates:** 4+ formats converted to real dates. Slash dates are day/month/year, because 1,402 train slash dates have a first part above 12 and none has a second part above 12. 910 slash dates are fully ambiguous, but follow the same rule.

## Still open (to handle in Stage 4/5)
- **190 ambiguous commas in train (79 in test)**, e.g. `radius_mean = 1,127`, which was treated as 1.127. It could really be 1127 (a wrong-unit value). The geometry check (radius vs perimeter vs area) in Stage 4 will decide.
- **Dates:** 47 train dates are invalid calendar dates (now empty) and 45 are outside the expected range, such as 2099-12-31, which looks like a placeholder. We treat both as missing, not as real dates.
- **Missing values remain** (about 410-490 per measurement column, and about 700 in each smoothness column). They are filled in Stage 5 using train-only statistics.
- **Wrong units and negative values** (area down to -452, radius up to 20,309): not touched yet.
- **Duplicates** (173 exact copies and 173 conflicting repeats in train): not touched yet.

In [75]:
import pandas as pd

from src.clean import clean_stage3, write_cleaning_log
from src.config import CLEAN_DIR

train_raw_stage3 = load_train()
test_raw_stage3 = load_test()

print("TRAIN Stage 3 diagnostics")
train_stage3, train_stage3_log = clean_stage3(train_raw_stage3)
print("TEST Stage 3 diagnostics")
test_stage3, test_stage3_log = clean_stage3(test_raw_stage3)

print("Training Stage 3 log entries")
display(pd.DataFrame(train_stage3_log))
print("Training cleaned dataframe info")
train_stage3.info()
print("Training NaN count per column")
display(train_stage3.isna().sum().rename("nan_count").to_frame())

CLEAN_DIR.mkdir(parents=True, exist_ok=True)
train_stage3.to_csv(CLEAN_DIR / "train_stage3.csv", index=False)
test_stage3.to_csv(CLEAN_DIR / "test_stage3.csv", index=False)
write_cleaning_log(train_stage3_log)
print(f"Saved cleaned train and test files to {CLEAN_DIR}")

TRAIN Stage 3 diagnostics
Comma numbers: decimal-comma cells=9919; thousands-comma cells=1389.
Ambiguous comma cells treated as decimal: 190; first 10 (column=value): [('radius_mean', '1,127'), ('radius_mean', '15,185'), ('radius_mean', '15,889'), ('radius_mean', '14,488'), ('radius_mean', '20,737'), ('radius_mean', '14,657'), ('radius_mean', '19,749'), ('radius_mean', '21,761'), ('radius_mean', '12,705'), ('radius_mean', '10,942')]
Unparseable numeric cells set to NaN: 0; remaining non-numeric values (column, value): []
NaN diagnosis labels: 0
Final class counts (y): {np.int64(0): 5494, np.int64(1): 3506}; malignant=38.96%
Centre counts: {'Site A': 3655, 'Site B': 3150, 'Site C': 2195}
Slash-date ambiguity: first part > 12=1402; second part > 12=0; both <= 12=910.
Unparseable dates set to NaT: 47
Date range: min=2025-01-05 00:00:00; max=2099-12-31 00:00:00; outside 2024-01-01..2026-12-31=45
TEST Stage 3 diagnostics
Comma numbers: decimal-comma cells=3320; thousands-comma cells=290.
Ambiguous comma cells treated as decimal: 79; first 10 (column=value): [('radius_mean', '13,892'), ('radius_mean', '12,917'), ('radius_mean', '20,959'), ('radius_mean', '18,628'), ('radius_mean', '13,518'), ('radius_mean', '13,315'), ('radius_mean', '11,981'), ('radius_mean', '12,633'), ('radius_mean', '19,219'), ('radius_mean', '15,302')]
Unparseable numeric cells set to NaN: 0; remaining non-numeric values (column, value): []
Centre counts: {'Site A': 1161, 'Site B': 1116, 'Site C': 723}
Slash-date ambiguity: first part > 12=436; second part > 12=0; both <= 12=321.
Unparseable dates set to NaT: 16
Date range: min=2025-01-05 00:00:00; max=2099-12-31 00:00:00; outside 2024-01-01..2026-12-31=12
Training Stage 3 log entries

,problem,columns,rows_affected,fix,why
0,Inconsistent column names,"texture_mean, perimeter_mean, concave_points_s...",0,Renamed 4 column headers; no data cells changed.,Consistent lowercase names with underscores ma...
1,Surrounding whitespace in text fields,"patient_id, exam_date, center, age, biopsy_fol...",3630,Stripped surrounding whitespace from 3630 cell...,Whitespace obscures otherwise identical identi...
2,Fake missing-value text in numeric fields,"radius_mean, radius_se, radius_worst, texture_...",14111,Replaced 14111 cells with NaN; counts by token...,These fixed missing-value spellings are not nu...
3,Numeric fields stored as text,"radius_mean, radius_se, radius_worst, texture_...",264889,Converted 264889 cells to float; decimal-comma...,The fixed parsing rules normalize number forma...
4,Inconsistent diagnosis labels,"diagnosis, y",15072,Standardized known labels to B/M and created i...,Only the specified benign and malignant spelli...
5,Inconsistent centre spelling or case,center,421,"Stripped and uppercased values, then standardi...",The data dictionary defines exactly three clin...
6,Exam dates stored in mixed formats,"exam_date, exam_date_raw",17953,"Parsed valid dates, retained original text in ...",Explicit formats and measured slash-date evide...

Training cleaned dataframe info
<class 'pandas.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 40 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   patient_id               9000 non-null   str
 1   exam_date                8953 non-null   datetime64[us]
 2   center                   9000 non-null   str
 3   age                      9000 non-null   float64
 4   biopsy_followup_code     9000 non-null   str
 5   radius_mean              8592 non-null   float64
 6   texture_mean             8570 non-null   float64
 7   perimeter_mean           8585 non-null   float64
 8   area_mean                8553 non-null   float64
 9   smoothness_mean          8305 non-null   float64
 10  compactness_mean         8588 non-null   float64
 11  concavity_mean           8583 non-null   float64
 12  concave_points_mean      8559 non-null   float64
 13  symmetry_mean            8550 non-null   float64
 14  fractal_dimension_mean   8508 non-null   float64
 15  radius_se                8555 non-null   float64
 16  texture_se               8576 non-null   float64
 17  perimeter_se             8561 non-null   float64
 18  area_se                  8583 non-null   float64
 19  smoothness_se            8292 non-null   float64
 20  compactness_se           8565 non-null   float64
 21  concavity_se             8548 non-null   float64
 22  concave_points_se        8539 non-null   float64
 23  symmetry_se              8549 non-null   float64
 24  fractal_dimension_se     8550 non-null   float64
 25  radius_worst             8556 non-null   float64
 26  texture_worst            8555 non-null   float64
 27  perimeter_worst          8536 non-null   float64
 28  area_worst               8524 non-null   float64
 29  smoothness_worst         8294 non-null   float64
 30  compactness_worst        8534 non-null   float64
 31  concavity_worst          8536 non-null   float64
 32  concave_points_worst     8525 non-null   float64
 33  symmetry_worst           8549 non-null   float64
 34  fractal_dimension_worst  8569 non-null   float64
 35  notes                    9000 non-null   str
 36  sample_ref               9000 non-null   str
 37  diagnosis                9000 non-null   str
 38  y                        9000 non-null   Int64
 39  exam_date_raw            9000 non-null   str
dtypes: Int64(1), datetime64[us](1), float64(31), str(7)
memory usage: 2.8 MB
Training NaN count per column

                         nan_count
patient_id                       0
exam_date                       47
center                           0
age                              0
biopsy_followup_code             0
radius_mean                    408
texture_mean                   430
perimeter_mean                 415
area_mean                      447
smoothness_mean                695
compactness_mean               412
concavity_mean                 417
concave_points_mean            441
symmetry_mean                  450
fractal_dimension_mean         492
radius_se                      445
texture_se                     424
perimeter_se                   439
area_se                        417
smoothness_se                  708
compactness_se                 435
concavity_se                   452
concave_points_se              461
symmetry_se                    451
fractal_dimension_se           450
radius_worst                   444
texture_worst                  445
perimeter_worst                464
area_worst                     476
smoothness_worst               706
compactness_worst              466
concavity_worst                464
concave_points_worst           475
symmetry_worst                 451
fractal_dimension_worst        431
notes                            0
sample_ref                       0
diagnosis                        0
y                                0
exam_date_raw                    0

Saved cleaned train and test files to C:\Users\SKY\Documents\Pink Ai\data\clean

# 3 Suspicious columns

# 4 Modelling and validation

# 5 Threshold

# 6 Submission